sudo: required
language: node_js
node_js:
- '8'
- '10'
services:
- cassandra
- redis
matrix:
  fast_finish: true

env:
  global:
    secure: "WkX9izOdqZTyiua9KB6Ig7+JEKwD6Q1UMoZ2vhXPIpfu5rmQ5Nxt4mLsCx9Xp11rP8qVkCsqq2zuT/91kAXxD+yD2YWw4xQJeE/fts8rjQ7VZUBSdn5OC+bdljF/oM5fh1x/YH7D+Jyv3OHiTzC0nmMvbSKxfVN4K5sBHvhYs57AGdAUWUDkUeiF1dS3ot8sBrHTr8pbdbd9IS3KdBHbX6RnEZViUnGnTbW2P8x0O12uHsPiMpN5yTdTpAvIni2ZmkvrpoaD1RFLcq4aVbbqGLPXwc/NMF8yWqjDutfn2Mc2Nhu+K0dEVpd4ZpeN3Qizp0VphAMZuYEY9lntvRXsAf1ewUFGe+kM57LXtFkrbxbVMVeo3e9wbJW6qq6D02tiG3uJcVNmzL0sgXy+O8wMgxEn78I3BOc+XEjXLnHtw78lnYPL3qH6b9nIGXL+DYK+eVvcMqhmM1f8SFrwsLVW3UoV/riXzULjn1hCkRYLi30z1kPk3AasTw7r8EtEtTTt2l9nanS/lV/LQukPJeMCvGgu+6kTmcieuAnIWLGfW6uiYlbfC57UjFCT+ZNKAK35uvOb+HEmKgUgsJ7piypm+pCci8eKH/LrG0HQI7C7PPPqHzxzqgkPFInyK2CahU58JJhLGLVnX6ngGTAX3MpJrPKW0LDJah93VxtFi/P1nUg="
