sudo: required
language: node_js

services:
  - redis
  - docker

node_js:
  - "8"
  - "10"

before_install:
  - docker pull localstack/localstack
  - docker run -d -p 127.0.0.1:4569:4569 -p 127.0.0.1:4572:4572 --name localstack localstack/localstack

install: npm install

matrix:
  fast_finish: true
