dist: trusty
sudo: required
language: node_js
node_js:
- '8'
- '10'

before_install:
- docker pull localstack/localstack
- docker run -d --name localstack -p 4569:4569 -p 4572:4572 --rm localstack/localstack

install: npm install
services:
- redis
matrix:
  fast_finish: true
